"""models relations reworked, added triggers for updated fields

Revision ID: 3c280375006d
Revises: f6b02e3aeec7
Create Date: 2024-02-09 19:27:13.637973

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3c280375006d'
down_revision: Union[str, None] = 'f6b02e3aeec7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('image', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'image', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'image', type_='foreignkey')
    op.drop_column('image', 'user_id')
    # ### end Alembic commands ###
